### ISSUE TITLE
Build Error while submitting Pull Request

### ISSUE THREAD

**Issue by zippopalermo** [mitmadness/UnityInvoker#2]
Hi, I would love to submit a pull request regarding error handling on spawning a Unity process. Unfortunately I'm running into an error in the CI build which keeps me from successfully submitting the PR. It's obviously not a problem with the code I'm submitting but apparently some problem running yarn in the CI, see below...

/usr/local/yarn-latest/lib/cli.js:46099

  let {

      ^

SyntaxError: Unexpected token {

    at exports.runInThisContext (vm.js:53:16)

    at Module._compile (module.js:373:25)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)

    at Object.<anonymous> (/usr/local/yarn-latest/bin/yarn.js:24:13)

    at Module._compile (module.js:409:26)

    at Object.Module._extensions..js (module.js:416:10)

Is there any way we can circumvent this?

**Comment by oktomus** [comment]
The latest CI runs smoothly now, i'm closing this
Thanks for submitting and issue :)
